r"""Deterministic REM-indexing oracle (review findings 1 and 4, round-3 corrected).

WHY A SEPARATE ORACLE IS NEEDED
-------------------------------
The folding oracle ($U U^{\dagger} U = U$ leaves the ideal distribution unchanged) runs
at ZERO readout noise, where every per-qubit response matrix is the identity and any
permutation of identities is the identity. It is therefore structurally blind to a
misindexed readout-mitigation matrix. That blindness is asserted below as a test.

ROUND-3 CORRECTIONS
-------------------
1. ORDERING. Statevector probabilities are indexed by PHYSICAL qubit; measured counts
   are indexed by CLASSICAL BIT. The previous version conflated them. The ideal
   distribution is now re-indexed explicitly via `ordering.phys_to_clbit_probs`, which
   is validated against an independent Aer measurement (test O1).
2. NON-CIRCULARITY. The previous version generated the noisy distribution with
   `rem.tensored()` and then recovered it by inverting that same matrix, so the
   reference was not independent. The noisy distribution is now generated by
   `ordering.apply_readout_bitwise`, a different code path that applies per-bit flip
   probabilities directly and is itself validated against Aer with a real
   `ReadoutError` model (test O2).
3. ASYMMETRIC STATES. The probe state is deliberately asymmetric, so a permutation
   cannot be invisible by symmetry.
"""
from __future__ import annotations
import sys, pathlib
import numpy as np
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))
from qiskit import QuantumCircuit, transpile
from qiskit.quantum_info import Statevector
from qiskit_aer import AerSimulator
from qiskit_aer.noise import NoiseModel, ReadoutError
from qemstudy.v2.circuits import measurement_map, BASIS_GATES
from qemstudy.v2.ordering import phys_to_clbit_probs, apply_readout_bitwise
from qemstudy.v2.rem import apply_rem

FAILS = []
def check(name, cond, detail=""):
    print(f"  [{'PASS' if cond else 'FAIL'}] {name}" + (f"  {detail}" if detail else ""))
    if not cond: FAILS.append(name)

P_ERR = {0: 0.30, 1: 0.02, 2: 0.15, 3: 0.05}      # deliberately unequal
LINE = [[0,1],[1,2],[2,3],[1,0],[2,1],[3,2]]
LAYOUTS = [[0,1,2,3], [3,2,1,0], [1,3,0,2], [2,0,3,1]]
N = 4


def resp(p): return np.array([[1-p, p], [p, 1-p]])
def mats_for(order): return np.stack([resp(P_ERR[q]) for q in order])


def probe(theta=0.9):
    """Asymmetric state: no permutation of it is invisible by symmetry."""
    qc = QuantumCircuit(N)
    qc.x(0); qc.ry(theta, 2); qc.cx(2, 3); qc.rz(0.4, 1); qc.h(1)
    qc.measure_all()
    return qc


def build(layout):
    return transpile(probe(), basis_gates=BASIS_GATES, coupling_map=LINE,
                     initial_layout=layout, optimization_level=1, seed_transpiler=0)


def ideal_clbit(t):
    p_phys = np.abs(Statevector.from_instruction(
        t.remove_final_measurements(inplace=False)).data) ** 2
    return phys_to_clbit_probs(p_phys, measurement_map(t))


print("\n=== O1. Re-indexing validated against an INDEPENDENT Aer measurement ===")
for layout in LAYOUTS:
    t = build(layout); mmap = measurement_map(t)
    p_cl = ideal_clbit(t)
    cnt = AerSimulator().run(t, shots=400000, seed_simulator=5).result().get_counts()
    emp = np.zeros(2**N); tot = sum(cnt.values())
    for b, v in cnt.items(): emp[int(b.replace(" ", ""), 2)] = v / tot
    p_raw = np.abs(Statevector.from_instruction(
        t.remove_final_measurements(inplace=False)).data) ** 2
    d_fix, d_raw = float(np.abs(p_cl-emp).max()), float(np.abs(p_raw-emp).max())
    check(f"re-indexed matches empirical, layout={layout} map={mmap}", d_fix < 5e-3,
          f"reindexed {d_fix:.1e} vs raw-statevector {d_raw:.1e}")
    if tuple(mmap) != tuple(range(N)):
        check(f"raw (unreindexed) statevector DISAGREES, layout={layout}", d_raw > 1e-2,
              f"{d_raw:.1e} — confirms the ordering bug is real")

print("\n=== O2. Bitwise readout channel validated against Aer's own ReadoutError ===")
t = build([1,3,0,2]); mmap = measurement_map(t)
nm = NoiseModel()
for q, e in P_ERR.items(): nm.add_readout_error(ReadoutError([[1-e, e], [e, 1-e]]), [q])
cnt = AerSimulator(noise_model=nm).run(t, shots=600000, seed_simulator=7).result().get_counts()
emp = np.zeros(2**N); tot = sum(cnt.values())
for b, v in cnt.items(): emp[int(b.replace(" ", ""), 2)] = v / tot
pred = apply_readout_bitwise(ideal_clbit(t), [P_ERR[mmap[c]] for c in range(N)])
check("independent bitwise channel matches Aer", float(np.abs(pred-emp).max()) < 5e-3,
      f"max|diff| = {np.abs(pred-emp).max():.1e}")

print("\n=== O3. Aligned vs misindexed calibration (generation path != inversion path) ===")
for layout in LAYOUTS:
    t = build(layout); mmap = measurement_map(t)
    p_ideal = ideal_clbit(t)
    # GENERATED bitwise; RECOVERED by tensored inversion -> not the same object.
    p_meas = apply_readout_bitwise(p_ideal, [P_ERR[mmap[c]] for c in range(N)])
    counts = {format(i, f"0{N}b"): p_meas[i]*1e6 for i in range(2**N) if p_meas[i] > 1e-15}

    def maxerr(order):
        rec, _ = apply_rem(counts, mats_for(order), N, clip=False)
        v = np.zeros(2**N)
        for b, c in rec.items(): v[int(b, 2)] = c/1e6
        return float(np.abs(v - p_ideal).max())

    e_ok, e_bad = maxerr(mmap), maxerr(tuple(range(N)))
    check(f"ALIGNED calibration recovers the exact ideal distribution, layout={layout}",
          e_ok < 1e-9, f"max|err| = {e_ok:.2e}")
    if tuple(mmap) == tuple(range(N)):
        check(f"identity map -> misindexing undetectable (expected), layout={layout}",
              e_bad < 1e-9, f"max|err| = {e_bad:.2e}")
    else:
        check(f"MISINDEXED calibration fails, layout={layout}", e_bad > 1e-3,
              f"max|err| = {e_bad:.2e} (aligned {e_ok:.2e})")

print("\n=== O4. Control: at ZERO readout noise the folding oracle cannot see this defect ===")
t = build([1,3,0,2]); p_ideal = ideal_clbit(t)
counts = {format(i, f"0{N}b"): p_ideal[i]*1e6 for i in range(2**N) if p_ideal[i] > 1e-15}
mats_id = np.stack([resp(0.0) for _ in range(N)])
a, _ = apply_rem(counts, mats_id, N, clip=False)
b, _ = apply_rem(counts, mats_id[[1,3,0,2]], N, clip=False)
check("with p=0 all response matrices are identity, so permuting them is invisible",
      all(abs(a.get(k,0)-b.get(k,0)) < 1e-9 for k in set(a)|set(b)),
      "-> the two defects require two independent oracles")

print("\n" + ("ALL TESTS PASSED" if not FAILS else f"{len(FAILS)} FAILURES: {FAILS}"))
sys.exit(1 if FAILS else 0)
